openapi: 3.0.0
info:
  title: Wichtel API
  version: 1.1.0
  description: ''
servers:
  - url: 'https://wichtel.me/api/v1'
    description: Production
  - url: 'http://wichtel.test/api/v1'
    description: Development
paths:
  /users:
    post:
      summary: Create new users
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  email:
                    type: string
                  api_token:
                    type: string
                  updated_at:
                    type: string
                    format: date-time
                  created_at:
                    type: string
                    format: date-time
      operationId: storeUser
      description: Create new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Mr. Grinch
                email:
                  type: string
                  format: email
                  example: grinch@greenMountian.com
              required:
                - name
                - email
        description: ''
      parameters: []
  /wichtelgroups:
    post:
      summary: Create new Wichtelgroup
      tags: []
      responses: {}
      operationId: post-wichtelgroups
    get:
      summary: List my Wichtelgroups
      tags: []
      responses: {}
      operationId: get-wichtelgroups
  '/wichtelgroups/{groupId}':
    parameters:
      - schema:
          type: string
        name: groupId
        in: path
        required: true
    get:
      summary: Show Wichtelgroup
      tags: []
      responses: {}
      operationId: get-wichtelgroups-wichtelgroupId
    put:
      summary: Update Wichtelgroup
      tags: []
      responses: {}
      operationId: put-wichtelgroups-wichtelgroupId
    delete:
      summary: Delete Wichtelgroup
      tags: []
      responses: {}
      operationId: delete-wichtelgroups-wichtelgroupId
  '/users/{userId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      summary: Show User
      tags: []
      responses: {}
      operationId: get-users-userId
    put:
      summary: Update User Information
      tags: []
      responses: {}
      operationId: put-users-userId
    delete:
      summary: Delete User
      tags: []
      responses: {}
      operationId: delete-users-userId
  '/wichtelgroups/{groupId}/wichtelmembers':
    parameters:
      - schema:
          type: string
        name: groupId
        in: path
        required: true
    get:
      summary: Show all Members of Group
      tags: []
      responses: {}
      operationId: get-wichtelgroups-groupId-wichtelmembers
    post:
      summary: Add Member to Group
      tags: []
      responses: {}
      operationId: post-wichtelgroups-groupId-wichtelmembers
  '/wichtelgroups/{groupId}/wichtelmembers/{memberId}':
    parameters:
      - schema:
          type: string
        name: groupId
        in: path
        required: true
      - schema:
          type: string
        name: memberId
        in: path
        required: true
    get:
      summary: Show Member Information
      tags: []
      responses: {}
      operationId: get-wichtelgroups-groupId-wichtelmembers-memberId
    put:
      summary: Update Member Information
      tags: []
      responses: {}
      operationId: put-wichtelgroups-groupId-wichtelmembers-memberId
    delete:
      summary: Remove Member from Group
      tags: []
      responses: {}
      operationId: delete-wichtelgroups-groupId-wichtelmembers-memberId
components:
  schemas: {}
